config/routes.rb
Erloncarlos::Application.routes.draw do
 

  

 

   resources :contacts
   resources :posts
   resources :clients
   resources :abouts
   resources :services
   resources :galleries
   root :to => "pages#index"
  

scope '/admin' do

  devise_for :users, :controllers => {

    :sessions => "admin/sessions",
    :passwords => "admin/passwords"
  }

end
  
  namespace :admin do
      resources :categories
      resources :contacts
      resources :types
      resources :galleries
      resources :posts
      resources :users
      root :to => "homes#index"

  end

  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name


  validates_presence_of :name
  default_scope :order => " name ASC"

  has_many :posts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :body, :email, :name, :title, :nickname

  default_scope :order => "created_at DESC"

 validates_presence_of :name , :email, :title
 validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i






  captcha :nickname
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :body, :title, :url, :foto, :type_id

   has_attached_file :foto, :styles => {:original =>"600x230#", :small => "920x350#", :medium => "290x100#", :thumb => "100x100>" }
   validates_attachment_presence :foto
   validates_attachment_size :foto, :less_than => 2.megabyte
   validates_attachment_content_type :foto, :content_type => %w(image/png image/jpeg image/gif)


   default_scope order("created_at DESC")

   belongs_to :type
   validates_associated :type
   validates_presence_of :title, :type_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :ativo, :body, :published, :subtitle, :title, :url, :category_id

  default_scope :order => "created_at DESC"

  belongs_to :category
  validates_presence_of :title, :category_id
  validates_associated :category
  #verifica se o post esta ativo ou não
  validates_inclusion_of :ativo, in:[true, false]

  def self.published
   where("ativo = ? AND published < ? ", false, Time.current)
  end


 


end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name

  has_many :galleries

  validates_presence_of :name

  default_scope :order => "name ASC"

end

app/models/user.rb
class User < ActiveRecord::Base
   devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
 

 
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	before_filter :controle_extra
  def index
  end



  def controle_extra
     @categories = Category.all
      @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.find(:all, :limit => 6, :order=> 'created_at desc')
     @posts_rodape = Post.find(:all, :limit => 1)
      @post_recentes = Post.find(:all, :limit => 4)
      @galleries_servicos = Type.find(3)

       
       @galleries_eventos = Type.find(4)
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::BaseController

  before_filter :controle_extras
 
  def index
    @galleries = Gallery.paginate page: params[:page], :per_page => 6
    respond_with @galleries
  end

  def show
    @gallery = Gallery.find(params[:id])
    respond_with @gallery
  end

  def new
    @gallery = Gallery.new
    respond_with @gallery 
  end


  def edit
    @gallery = Gallery.find(params[:id])
  end

  def create
    @gallery = Gallery.new(params[:gallery])
    flash[:notice] = "Registro salvo com sucesso !" if @gallery.save
    respond_with @gallery, :location => admin_galleries_path
    
  end

 
  def update
    @gallery = Gallery.find(params[:id])
    flash[:notice] = "Registro atualizado com sucesso ! " if @gallery.update_attributes(params[:gallery])
    respond_with @gallery, :location => admin_galleries_path
 
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    respond_with @gallery, :location => admin_galleries_path
  end


  def controle_extras
    @types = Type.all
     @galleries =  Gallery.paginate page: params[:page], :per_page => 12
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
		 before_filter :load_resources
    def index
    @galleries = Gallery.scoped.paginate page: params[:page], :per_page => 2
    @galleries = @type.galleries if @type.present?
    respond_with @galleries

    end

    def show
    @gallery = Gallery.published.find(params[:id])
    respond_with @gallery
    end

    private

    def load_resources


    @categories = Category.all
    @category   = Category.find(params[:category_id]) if params[:category_id]
    @galleries = Gallery.find(:all, :limit => 2, :order=> 'created_at desc')
    @posts_rodape = Post.find(:all, :limit => 1)
    @post_recentes = Post.find(:all, :limit => 4)
      #--------------------------------------------------------------------------

    @types = Type.paginate page: params[:page], :per_page => 2
    @type   = Type.find(params[:type_id]) if params[:type_id]
    #@galleries = Gallery.all   
     @types_clientes = Type.find(2)
   
     @galleries_servicos = Type.find(3)
     @galleries_eventos = Type.find(4)



    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

before_filter :controle_extra
  def index
       @galleries = Gallery.paginate page: params[:page], :per_page => 12
  end
  def controle_extra
     @categories = Category.all
      @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.find(:all, :limit => 6, :order=> 'created_at desc')
     @posts_rodape = Post.find(:all, :limit => 1)
      @post_recentes = Post.find(:all, :limit => 4)
      @galleries_servicos = Type.find(3)
       
       @galleries_eventos = Type.find(4)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_filter :controle_extra
	
  def index
  end


  def controle_extra
     @categories = Category.all
      @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.find(:all, :limit => 6, :order=> 'created_at desc')
     @posts_rodape = Post.find(:all, :limit => 1)
      @post_recentes = Post.find(:all, :limit => 4)
      @galleries_servicos = Type.find(3)
       @galleries_eventos = Type.find(4)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :controle_extra

	def index
      @posts = Post.paginate page: params[:page], :per_page => 3
      #filtar os posts por categoria
       @posts = @category.posts if @category.present?
       @posts = @posts.published.paginate page: params[:page], :per_page => 3
       respond_with @posts

	end

	def show

		 @post = Post.find(params[:id])
         respond_with @post
	end

	def controle_extra
     @categories = Category.all
     #filtra os posts por catregorias
     @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.all
     @posts_rodape = Post.find(:all, :limit => 1)
       @galleries_servicos = Type.find(3)
       @galleries_eventos = Type.find(4)
     @post_recentes = Post.find(:all, :limit => 15)
	end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	def textilize(text)
    RedCloth.new(text).to_html.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/galleries/_form.html.erb
<article class="module width_full">
<header><h3>Cadastro imagens</h3></header>
<div class="module_content">

  <%= form_for [:admin, @gallery] do |f| %>
    <% if @gallery.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@gallery.errors.count, "error") %> : Não foi possível salvar o registro no banco:</h2>
    <% @gallery.errors.full_messages.each do |msg| %>
    <h4 class="alert_error"><%= msg %></h4>
    <% end %>

    </div>
    <% end %>

    <div class="imagempost">

 <div id=".media">
<div class="media">
<%- @galleries.each do |g| -%>
  <%= link_to image_tag(g.foto.url(:thumb))   %>
<%- end -%>
</div>
</div>
<%= will_paginate @galleries %>

 </div> 
    <fieldset>  
    <label>Selecione a categoria</label>
     <%= f.collection_select(:type_id, @types, :id ,:name, :prompt => true ) %> 

    </fieldset>
      <fieldset>
      <label>Nome</label>
      <%= f.text_field :title %>
      </fieldset>
      <fieldset>
      <label>Endereço do site</label>
      <%= f.text_field :url %>
      </fieldset>
      <fieldset>
       <label>Descrição da imagem</label>
       <%= f.text_area :body, :rows => "3"  %>
      </fieldset>
      <fieldset>
       <%= f.file_field :foto %>
      </fieldset>
    </div>
    <footer>
    <div class="submit_link">
      <%= f.submit 'Salvar registro',:class => 'alt_btn' %>
     <%= link_to admin_galleries_path do %>
Cancelar
<% end %>
    </div>
    </footer>
  <% end %>  
</article><!-- end of post new article -->  
<div class="spacer"></div>

app/views/admin/galleries/edit.html.erb
<%= render 'form' %>

app/views/admin/galleries/index.html.erb
<article class="module width_3_quarter">
<% if notice.present? %>
  <h4 class="alert_success"><%= notice %></h4>
  <% end %>
<header><h3 class="tabs_involved">Imagens cadastradas</h3>
<ul class="tabs">
<li><%= link_to new_admin_gallery_path, :title => "Criar novo registro" do %>
  Novo registro<% end %></li>

</ul>
</header>

<div class="tab_container">
<div id="tab1" class="tab_content">
  <table class="tablesorter" cellspacing="0"> 
    <thead> 
    <tr>   
    <th>Código</th>
    <th>Nome</th>
    <th>Imagem</th>    
    <th>Ações</th> 
    </tr> 
    </thead> 
    <tbody>
    <% if@galleries.present? %>
    <% @galleries.each  do |c| %> 
    <tr> 
  
    <td width="100px"><%= c.id %></td>
    <td><%= c.title %></td> 
    <td>imagem</td>
    
    <td width="120px">
      <%= link_to edit_admin_gallery_path(c) do %>
      <%= image_tag "admin/icn_edit.png" , :title => "Editar registro " %>
     
      <% end %>
       <%= link_to admin_gallery_path(c) do %>
      <%= image_tag "admin/icn_search.png" , :title => "Visualizar registro " %>
     
      <% end %>
       
      <%= link_to admin_gallery_path(c), confirm: 'Deletar arquivo, Tem certeza ?', method: :delete , :title => "Excluir arquivo"  do %>
       <%= image_tag "admin/icn_trash.png"  %>
     
      <% end %>
   </td> 
       
    </tr> 

         <% end %>  
    <% end %>

<tr>
<td colspan="6" align="center"><%= will_paginate @galleries %></td>
</tr>

    </tbody> 
  </table>
  
</div><!-- end of #tab1 -->

</div><!-- end of .tab_container -->

</article><!-- end of content manager article -->
<div class="clear"></div>

app/views/admin/galleries/show.html.erb
<article class="module width_full">
<header><h3>Detalhes da imagem</h3></header>
<div class="module_content">
	
<%= image_tag @gallery.foto.url %>
<%= image_tag @gallery.foto.url(:medium) %>
<%= image_tag @gallery.foto.url(:thumb) %>
	<p>

	<%= link_to admin_galleries_path do %>
	Voltar
	<% end %>
	</p>

</div>
</article><!-- end of styles article -->
<div class="spacer"></div>