config/routes.rb
Erloncarlos::Application.routes.draw do
 

  

 

   resources :contacts
   resources :posts
   resources :clients
   resources :abouts
   resources :services
   resources :galleries
   root :to => "pages#index"
  

scope '/admin' do

  devise_for :users, :controllers => {

    :sessions => "admin/sessions",
    :passwords => "admin/passwords"
  }

end
  
  namespace :admin do
      resources :categories
      resources :contacts
      resources :types
      resources :galleries
      resources :posts
      resources :users
      root :to => "homes#index"

  end

  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name


  validates_presence_of :name
  default_scope :order => " name ASC"

  has_many :posts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :body, :email, :name, :title, :nickname

  default_scope :order => "created_at DESC"

 validates_presence_of :name , :email, :title
 validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i






  captcha :nickname
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :body, :title, :url, :foto, :type_id

   has_attached_file :foto, :styles => {:original =>"600x230#", :small => "920x350#", :medium => "290x100#", :thumb => "100x100>" }
   validates_attachment_presence :foto
   validates_attachment_size :foto, :less_than => 2.megabyte
   validates_attachment_content_type :foto, :content_type => %w(image/png image/jpeg image/gif)


   default_scope order("created_at DESC")

   belongs_to :type
   validates_associated :type
   validates_presence_of :title, :type_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :ativo, :body, :published, :subtitle, :title, :url, :category_id

  default_scope :order => "created_at DESC"

  belongs_to :category
  validates_presence_of :title, :category_id
  validates_associated :category
  #verifica se o post esta ativo ou não
  validates_inclusion_of :ativo, in:[true, false]

  def self.published
   where("ativo = ? AND published < ? ", false, Time.current)
  end


 


end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name

  has_many :galleries

  validates_presence_of :name

  default_scope :order => "name ASC"

end

app/models/user.rb
class User < ActiveRecord::Base
   devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
 

 
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	before_filter :controle_extra
  def index
  end



  def controle_extra
     @categories = Category.all
      @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.find(:all, :limit => 6, :order=> 'created_at desc')
     @posts_rodape = Post.find(:all, :limit => 1)
      @post_recentes = Post.find(:all, :limit => 4)
      @galleries_servicos = Type.find(3)

       
       @galleries_eventos = Type.find(4)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::BaseController

	
  def index
     @contacts = Contact.paginate page:params[:page], :per_page => 10
     respond_with @contact
  end

 
  def show
    @contact = Contact.find(params[:id])
     respond_with @contact
  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	before_filter :controle_extra
	
  def index
  end


  def controle_extra
     @categories = Category.all
      @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.find(:all, :limit => 6, :order=> 'created_at desc')
     @posts_rodape = Post.find(:all, :limit => 1)
      @post_recentes = Post.find(:all, :limit => 4)
      @galleries_servicos = Type.find(3)
       @galleries_eventos = Type.find(4)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :controle_extra

	def index
      @posts = Post.paginate page: params[:page], :per_page => 3
      #filtar os posts por categoria
       @posts = @category.posts if @category.present?
       @posts = @posts.published.paginate page: params[:page], :per_page => 3
       respond_with @posts

	end

	def show

		 @post = Post.find(params[:id])
         respond_with @post
	end

	def controle_extra
     @categories = Category.all
     #filtra os posts por catregorias
     @category   = Category.find(params[:category_id]) if params[:category_id]
     @galleries = Gallery.all
     @posts_rodape = Post.find(:all, :limit => 1)
       @galleries_servicos = Type.find(3)
       @galleries_eventos = Type.find(4)
     @post_recentes = Post.find(:all, :limit => 15)
	end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	def textilize(text)
    RedCloth.new(text).to_html.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/homes/_sidebar.html.erb
<form class="quick_search">
<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
</form>
<hr/>
<h3>Cadastros</h3>
<ul class="toggle">
<li class="icn_new_article"><%= link_to new_admin_category_path do %>
	Categorias
	<% end %></li>
	<li class="icn_new_article"><%= link_to new_admin_type_path do %>
	Categorias de fotos
	<% end %></li>
	<li class="icn_profile"><%= link_to new_admin_gallery_path do %>
	Imagens
	<% end %></li>
<li class="icn_edit_article"><%= link_to new_admin_post_path  do %>
   Artigos
   <% end %>
</li>
<li class="icn_add_user"><%= link_to new_admin_user_path  do %>
   Usuário
   <% end %>
</li>
<li class="icn_categories"><a href="#">Categories</a></li>
<li class="icn_tags"><a href="#">Tags</a></li>
</ul>

<h3>Relatórios</h3>
<ul class="toggle">
<li class="icn_categories"><%= link_to admin_contacts_path do %>
	Contatos<% end %></li>
<li class="icn_categories"><%= link_to admin_categories_path do %>
	Categorias<% end %></li>
	<li class="icn_categories"><%= link_to admin_types_path do %>
	Categorias de Fotos<% end %></li>
	<li class="icn_profile"><%= link_to admin_galleries_path do %>
	Imagens<% end %></li>
<li class="icn_edit_article"><%= link_to admin_posts_path do %>
	Artigos<% end %></li>
	<li class="icn_view_users"><%= link_to admin_users_path do %>
	Usuários<% end %></li>
<li class="icn_categories"><a href="#">Video</a></li>
</ul>

<h3>Admin</h3>
<ul class="toggle">
<li >Ip: </li>
<li >Ultino acesso :</li>
<li class="icn_jump_back"> 
                   <%= link_to  destroy_user_session_path, :method => :delete, :title => "Sair do sistema"  do %>
                    <span>Sair</span>
                    <% end %> 
                     </li>
</ul>

<footer>
<hr />
<p><strong>Copyright &copy; 2011 Website Admin</strong></p>
<p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
</footer>

app/views/admin/homes/index.html.erb
		
		<article class="module width_full">
			<header><h3>Status do sistema</h3></header>
			<div class="module_content">
				<article class="stats_graph">
					<img src="http://chart.apis.google.com/chart?chxr=0,0,3000&chxt=y&chs=520x140&cht=lc&chco=76A4FB,80C65A&chd=s:Tdjpsvyvttmiihgmnrst,OTbdcfhhggcTUTTUadfk&chls=2|2&chma=40,20,20,30" width="520" height="140" alt="" />
				</article>
				
				<article class="stats_overview">
					<div class="overview_today">
						<p class="overview_day">Today</p>
						<p class="overview_count">1,876</p>
						<p class="overview_type">Hits</p>
						<p class="overview_count">2,103</p>
						<p class="overview_type">Views</p>
					</div>
					<div class="overview_previous">
						<p class="overview_day">Yesterday</p>
						<p class="overview_count">1,646</p>
						<p class="overview_type">Hits</p>
						<p class="overview_count">2,054</p>
						<p class="overview_type">Views</p>
					</div>
				</article>
				<div class="clear"></div>
			</div>
		</article><!-- end of stats article -->



<article class="module width_3_quarter">
<header><h3 class="tabs_involved">Mensagens enviadas do site</h3>
<ul class="tabs">
<li><a href="#tab1">Contatos</a></li>

</ul>
</header>

<div class="tab_container">
<div id="tab1" class="tab_content">
	<table class="tablesorter" cellspacing="0"> 
		<thead> 
		<tr> 
		<th></th> 
		<th>Data</th>
		<th>Nome</th> 
		<th>Email</th> 
		<th>Assunto</th> 
		<th>Ações</th> 
		</tr> 
		</thead> 
		<tbody>
		<% if@contacts.present? %>
		<% @contacts.each  do |c| %> 
		<tr> 
		<td><input type="checkbox"></td>
		<td><%= c.created_at.strftime("%d de %b - %y") %></td> 
		<td><%= c.name %></td> 
		<td><%= c.email %></td> 
		<td><%= c.title %></td> 
		<td><%= link_to admin_contact_path(c) do %>
			<%= image_tag "admin/icn_alert_info.png" , :title => "Visualizar contato "%>
			<% end %>
		<%= image_tag "admin/icn_trash.png" , :title => "Enviar email" %></td> 
		</tr> 

         <% end %>  
		<% end %>

<tr>
<td colspan="6" align="center"><%= will_paginate @contacts %></td>
</tr>

		</tbody> 
	</table>
	
</div><!-- end of #tab1 -->

</div><!-- end of .tab_container -->

</article><!-- end of content manager article -->
<div class="clear"></div>	
	